version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    user: '1000:1000'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5433'

volumes:
  postgres_data:
