# pull official base image
FROM osgeo/gdal as base

# set work directory


RUN useradd -ms /bin/bash newuser
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update
RUN apt-get install -y python3.9
RUN apt-get install -y python3-pip
RUN apt-get install -y netcat

#RUN apt-get update &&\
#    apt-get install -y binutils libproj-dev gdal-bin

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh



# copy project
COPY . .

RUN usermod -u 1000 newuser;

USER newuser

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]